parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 90
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      py38:
        ENV_FILE: ci/deps/actions-38.yaml
        CONDA_PY: "38"

      py39:
        ENV_FILE: ci/deps/actions-39.yaml
        CONDA_PY: "39"

      py310:
        ENV_FILE: ci/deps/actions-310.yaml
        CONDA_PY: "310"

  steps:
    - script: echo '##vso[task.prependpath]$(HOME)/miniconda3/bin'
      displayName: 'Set conda path'

    - script: rm /usr/local/miniconda/pkgs/cache/*.json
      displayName: 'Workaround for mamba-org/mamba#488'

    - script: ci/setup_env.sh
      displayName: 'Setup environment and build pandas'

    - script: |
        conda run -n pandas-dev --no-capture-output ci/run_tests.sh
      displayName: 'Test'

    - script: |
        pushd /tmp
        conda run -n pandas-dev python -c "import pandas; pandas.show_versions()"
        popd
      displayName: 'Build versions'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        failTaskOnFailedTests: true
        testResultsFiles: 'test-data.xml'
        testRunTitle: ${{ format('{0}-$(CONDA_PY)', parameters.name) }}
      displayName: 'Publish test results'
