parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 90
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      py38:
        ENV_FILE: ci/deps/actions-38.yaml
        CONDA_PY: "38"

      py39:
        ENV_FILE: ci/deps/actions-39.yaml
        CONDA_PY: "39"

      py310:
        ENV_FILE: ci/deps/actions-310.yaml
        CONDA_PY: "310"

  steps:
    - powershell: |
        Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
        Write-Host "##vso[task.prependpath]$HOME/miniconda3/bin"
      displayName: 'Add conda to PATH'
    - bash: conda install -yv -c conda-forge -n base 'mamba>=0.21.2'
      displayName: 'Install mamba'

    - bash: |
        # See https://github.com/mamba-org/mamba/issues/1370
        # See https://github.com/mamba-org/mamba/issues/633
        C:\\Miniconda\\condabin\\mamba.bat create -n pandas-dev
        C:\\Miniconda\\condabin\\mamba.bat env update -n pandas-dev --file ci\\deps\\actions-$(CONDA_PY).yaml
        # TODO: GH#44980 https://github.com/pypa/setuptools/issues/2941
        C:\\Miniconda\\condabin\\mamba.bat install -n pandas-dev 'setuptools<60'
        C:\\Miniconda\\condabin\\mamba.bat list -n pandas-dev
      displayName: 'Create anaconda environment'
    - bash: |
        source activate pandas-dev
        conda list
        python setup.py build_ext -q -j 2
        python -m pip install --no-build-isolation -e .
      displayName: 'Build'
    - bash: |
        source activate pandas-dev
        wmic.exe cpu get caption, deviceid, name, numberofcores, maxclockspeed
        ci/run_tests.sh
      displayName: 'Test'
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        failTaskOnFailedTests: true
        testResultsFiles: 'test-data.xml'
        testRunTitle: ${{ format('{0}-$(CONDA_PY)', parameters.name) }}
      displayName: 'Publish test results'
