name: Set up pandas
description: Runs all the setup steps required to have a built pandas ready to use
runs:
  using: composite
  steps:
    - name: Setting conda path
      run: echo "${HOME}/miniconda3/bin" >> $GITHUB_PATH
      shell: bash -el {0}

    - name: Setup environment and build pandas
      run: ci/setup_env.sh
      shell: bash -el {0}
